// Mock Database for Netflix (using high-speed Unsplash, TMDB-fallback and Wikipedia CDN proxies)

// Dynamic seasons/episodes generator for mock TV shows to keep bundle size small and load speeds instant!
export const generateMockSeasons = (show) => {
  const seasonsCount = show.seasons_count || 1;
  const seasons = [];

  for (let s = 1; s <= seasonsCount; s++) {
    const episodes = [];
    // Season 1 has 8 episodes, other seasons have 6
    const episodeCount = s === 1 ? 8 : 6;

    for (let e = 1; e <= episodeCount; e++) {
      episodes.push({
        episode_number: e,
        title: `Episode ${e}: ${show.title} Special`,
        runtime: "48m",
        overview: `Episode ${e} of ${show.title}. The stakes are raised as the story dives deeper into characters' hidden motives, complex relationships, and high-tension decisions in this acclaimed chapter.`
      });
    }
    seasons.push({
      season_number: s,
      name: `Season ${s}`,
      episodes
    });
  }
  return seasons;
};

// ----------------------------------------------------
// 1. MOVIES (Total: 75 titles - 5 Original + 70 New)
// ----------------------------------------------------
export const mockMovies = [
  // --- Original 5 Hollywood Movies ---
  {
    id: "157336",
    title: "Interstellar",
    overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo5AAAtpGz1XMpfShMxf5hxz358sacrXQhXg&s",
    poster_path: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=400",
    media_type: "movie",
    release_date: "2014-11-05",
    vote_average: 8.4,
    match_percentage: 98,
    genres: ["Adventure", "Drama", "Science Fiction"],
    duration: "2h 49m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "27205",
    title: "Inception",
    overview: "Cobb, a skilled thief who steals valuable secrets from deep within the subconscious during the dream state, is offered a chance to have his history erased as payment for a seemingly impossible task: \"inception\", the implantation of another person's idea into their subconscious.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ-NdSkCXltfzt5cpgFV5dmFenxfJtTdP_sQ&s",
    poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400",
    media_type: "movie",
    release_date: "2010-07-15",
    vote_average: 8.3,
    match_percentage: 96,
    genres: ["Action", "Science Fiction", "Adventure"],
    duration: "2h 28m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "693134",
    title: "Dune: Part Two",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZgrSsmZ4T28XiAERvBPbHaU-OlvJhUyEe-A&s",
    poster_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=400",
    media_type: "movie",
    release_date: "2024-02-27",
    vote_average: 8.2,
    match_percentage: 99,
    genres: ["Science Fiction", "Adventure", "Drama"],
    duration: "2h 46m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "76600",
    title: "Avatar: The Way of Water",
    overview: "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    backdrop_path: "https://static0.colliderimages.com/wordpress/wp-content/uploads/2022/11/avatar-the-way-of-water-poster.jpg",
    poster_path: "https://images.unsplash.com/photo-1500485035595-cbe6f645feb1?q=80&w=400",
    media_type: "movie",
    release_date: "2022-12-14",
    vote_average: 7.6,
    match_percentage: 92,
    genres: ["Science Fiction", "Action", "Adventure"],
    duration: "3h 12m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "155",
    title: "The Dark Knight",
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTZNapmWwK7Tcvhg9D6biwKVT_GStDyxQhIg&s",
    poster_path: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=400",
    media_type: "movie",
    release_date: "2008-07-16",
    vote_average: 8.5,
    match_percentage: 97,
    genres: ["Drama", "Action", "Crime", "Thriller"],
    duration: "2h 32m",
    age_rating: "PG-13",
    industry: "hollywood"
  },

  // --- 35 New Hollywood Movies ---
  {
    id: "872585",
    title: "Oppenheimer",
    overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II, bringing about the nuclear age.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS57OPGJnEeEtY18zB01dHv_uNMxY8-lAohBA&s",
    poster_path: "https://images.unsplash.com/photo-1447069387593-a5de0862481e?q=80&w=400",
    media_type: "movie",
    release_date: "2023-07-19",
    vote_average: 8.4,
    match_percentage: 97,
    genres: ["Drama", "History", "Biography"],
    duration: "3h 0m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "346698",
    title: "Barbie",
    overview: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdShaYR7hTxxqWs-qeCAPyZBSJoj8D_nmhxA&s",
    poster_path: "https://images.unsplash.com/photo-1559583985-c80d8ad9b29f?q=80&w=400",
    media_type: "movie",
    release_date: "2023-07-19",
    vote_average: 7.2,
    match_percentage: 88,
    genres: ["Comedy", "Adventure", "Fantasy"],
    duration: "1h 54m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "324857",
    title: "Spider-Man: Into the Spider-Verse",
    overview: "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp8LvVJfqW803QQRGJDL5XJSIra2hthjwDXA&s",
    poster_path: "https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=400",
    media_type: "movie",
    release_date: "2018-12-07",
    vote_average: 8.4,
    match_percentage: 99,
    genres: ["Action", "Adventure", "Animation", "Science Fiction"],
    duration: "1h 57m",
    age_rating: "PG",
    industry: "hollywood"
  },
  {
    id: "299534",
    title: "Avengers: Endgame",
    overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn_SMWSRj6PFLBLg1egL9_ozGVJWr1-4Y14A&s",
    poster_path: "https://images.unsplash.com/photo-1608889175123-8ec330b86f84?q=80&w=400",
    media_type: "movie",
    release_date: "2019-04-24",
    vote_average: 8.3,
    match_percentage: 98,
    genres: ["Action", "Adventure", "Science Fiction"],
    duration: "3h 1m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "603",
    title: "The Matrix",
    overview: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPEXLZx6uHstm9qFijCGb8_SkTBYDsaaUASQ&s",
    poster_path: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=400",
    media_type: "movie",
    release_date: "1999-03-30",
    vote_average: 8.2,
    match_percentage: 95,
    genres: ["Action", "Science Fiction"],
    duration: "2h 16m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "597",
    title: "Titanic",
    overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later, and the star-crossed romance she shared with young artist Jack Dawson.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfjp86pxOuh934rfZExbc6IBAIgyVEOFp2Kw&s",
    poster_path: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=400",
    media_type: "movie",
    release_date: "1997-11-18",
    vote_average: 7.9,
    match_percentage: 91,
    genres: ["Drama", "Romance", "History"],
    duration: "3h 14m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "98",
    title: "Gladiator",
    overview: "In the year 180, the death of Emperor Marcus Aurelius throws the Roman Empire into chaos. Maximus is one of the Roman army's most capable and trusted generals. When the emperor's corrupt son Commodus takes power, Maximus is arrested and slated for execution.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwkDZ9HWefEWMFRGtiyWTd4dSBfe0JF9uT-g&s",
    poster_path: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?q=80&w=400",
    media_type: "movie",
    release_date: "2000-05-01",
    vote_average: 8.2,
    match_percentage: 96,
    genres: ["Action", "Adventure", "Drama"],
    duration: "2h 35m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "680",
    title: "Pulp Fiction",
    overview: "A burger-loving hitman, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that weave back and forth in time.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQxwLhM3CtpWUmgSkxyf69Eg0Vsun-1AIwwQ&s",
    poster_path: "https://images.unsplash.com/photo-1593085512500-5d55148d6f0d?q=80&w=400",
    media_type: "movie",
    release_date: "1994-09-10",
    vote_average: 8.5,
    match_percentage: 98,
    genres: ["Thriller", "Crime"],
    duration: "2h 34m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "238",
    title: "The Godfather",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone, survives an attempt on his life, his youngest son, Michael, steps in to take control of the killers.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWeoswLVpPz1uYTc0xGs58VtRnzaVI15ceyA&s",
    poster_path: "https://images.unsplash.com/photo-1533928298208-27ff66555d8d?q=80&w=400",
    media_type: "movie",
    release_date: "1972-03-14",
    vote_average: 8.7,
    match_percentage: 99,
    genres: ["Drama", "Crime"],
    duration: "2h 55m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "329",
    title: "Jurassic Park",
    overview: "A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA. Before opening day, he invites a team of experts and his two eager grandchildren to experience the park and pacify anxious investors.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSafNHNpH7eMpa48A6fZdTji8emQiOGDxmgig&s",
    poster_path: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=400",
    media_type: "movie",
    release_date: "1993-06-11",
    vote_average: 8.0,
    match_percentage: 94,
    genres: ["Adventure", "Science Fiction"],
    duration: "2h 7m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "278",
    title: "The Shawshank Redemption",
    overview: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsMach1XU5x2BuK3jFfUXCTiRCIl1-bcnfPQ&s",
    poster_path: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=400",
    media_type: "movie",
    release_date: "1994-09-23",
    vote_average: 8.7,
    match_percentage: 99,
    genres: ["Drama", "Crime"],
    duration: "2h 22m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "335984",
    title: "Blade Runner 2049",
    overview: "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSleYhCZ5zWB9olxJaX4hX_wcE7VPWm0Ckvg&s",
    poster_path: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=400",
    media_type: "movie",
    release_date: "2017-10-04",
    vote_average: 7.5,
    match_percentage: 91,
    genres: ["Science Fiction", "Drama", "Thriller"],
    duration: "2h 44m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "76341",
    title: "Mad Max: Fury Road",
    overview: "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and almost everyone is crazed fighting for the necessities of life.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWItAqpZI9hwgxcgpzgO6AxJrPGxO0-FqSfA&s",
    poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400",
    media_type: "movie",
    release_date: "2015-05-13",
    vote_average: 7.6,
    match_percentage: 94,
    genres: ["Action", "Science Fiction", "Adventure"],
    duration: "2h 0m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "361743",
    title: "Top Gun: Maverick",
    overview: "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtVyv03egBW47swH6UaJkUBBWSlAMYdpDKWA&s",
    poster_path: "https://images.unsplash.com/photo-1519074002996-a69e7ac46a42?q=80&w=400",
    media_type: "movie",
    release_date: "2022-05-24",
    vote_average: 8.2,
    match_percentage: 96,
    genres: ["Action", "Drama"],
    duration: "2h 10m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "545611",
    title: "Everything Everywhere All at Once",
    overview: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.",
    backdrop_path: "https://m.media-amazon.com/images/S/pv-target-images/280624c4631999ef41fb2a63c0f5885d328b0e8da5c181f46c5f26f083c3be9f.jpg",
    poster_path: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=400",
    media_type: "movie",
    release_date: "2022-03-24",
    vote_average: 7.8,
    match_percentage: 93,
    genres: ["Action", "Comedy", "Science Fiction", "Adventure"],
    duration: "2h 19m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "244786",
    title: "Whiplash",
    overview: "Under the direction of a ruthless instructor, a talented young drummer at a prestigious music conservatory begins to lose his humanity in his quest to achieve musical perfection.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2pxe2mwFxFUx9dCwkgt4DVK0MtvlAn3NRiw&s",
    poster_path: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=400",
    media_type: "movie",
    release_date: "2014-10-10",
    vote_average: 8.4,
    match_percentage: 96,
    genres: ["Drama", "Music"],
    duration: "1h 47m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "106646",
    title: "The Wolf of Wall Street",
    overview: "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS_lhxZL_sXx-v3tnJJonqA5COY89CWCKHSg&s",
    poster_path: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=400",
    media_type: "movie",
    release_date: "2013-12-25",
    vote_average: 8.0,
    match_percentage: 95,
    genres: ["Comedy", "Drama", "Crime"],
    duration: "3h 0m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "313369",
    title: "La La Land",
    overview: "Mia, an aspiring actress, and Sebastian, a dedicated jazz musician, struggle to make ends meet in a city known for crushing hopes and breaking hearts. Set in modern-day Los Angeles, this original musical about everyday life explores the joy and pain of pursuing your dreams.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc0cfmm-oi4V8Th29x7IcN-oItrKGd6sn9zg&s",
    poster_path: "https://images.unsplash.com/photo-1460881680858-30d872d5b530?q=80&w=400",
    media_type: "movie",
    release_date: "2016-11-29",
    vote_average: 7.9,
    match_percentage: 92,
    genres: ["Romance", "Drama", "Comedy", "Music"],
    duration: "2h 8m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "496243",
    title: "Parasite",
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSj5sKOTQZE3otWP1q_uBAe1kJPG0Vi2aA_2Q&s",
    poster_path: "https://images.unsplash.com/photo-1535083783855-76ae62b2914e?q=80&w=400",
    media_type: "movie",
    release_date: "2019-05-30",
    vote_average: 8.5,
    match_percentage: 98,
    genres: ["Comedy", "Thriller", "Drama"],
    duration: "2h 12m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "546554",
    title: "Knives Out",
    overview: "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate.",
    backdrop_path: "https://static0.srcdn.com/wordpress/wp-content/uploads/2021/04/knives-out-netflix-.jpg",
    poster_path: "https://images.unsplash.com/photo-1585647347483-22b66260dfff?q=80&w=400",
    media_type: "movie",
    release_date: "2019-11-27",
    vote_average: 7.8,
    match_percentage: 93,
    genres: ["Comedy", "Mystery", "Thriller"],
    duration: "2h 10m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "419430",
    title: "Get Out",
    overview: "Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family's overly accommodating behavior as nervous attempts to deal with their daughter's interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he could never have imagined.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV4ThMGYAiUT2s555EsQH3exfuuI6MmrPysg&s",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "movie",
    release_date: "2017-02-24",
    vote_average: 7.6,
    match_percentage: 90,
    genres: ["Mystery", "Thriller", "Horror"],
    duration: "1h 44m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "447332",
    title: "A Quiet Place",
    overview: "A family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxxyass9_YVVZM2In5fMx2C3MFr2TnQCZKoA&s",
    poster_path: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=400",
    media_type: "movie",
    release_date: "2018-04-03",
    vote_average: 7.4,
    match_percentage: 89,
    genres: ["Drama", "Science Fiction", "Horror"],
    duration: "1h 37m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "567189",
    title: "Ford v Ferrari",
    overview: "American car designer Carroll Shelby and the British-born driver Ken Miles work together to battle corporate interference, the laws of physics, and their own personal demons to build a revolutionary race car for Ford Motor Company and take on the dominating race cars of Enzo Ferrari at the 24 Hours of Le Mans in France in 1966.",
    backdrop_path: "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/caradvice/private/rkzx71auslyqdluudh9j",
    poster_path: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=400",
    media_type: "movie",
    release_date: "2019-11-13",
    vote_average: 8.0,
    match_percentage: 95,
    genres: ["Drama", "Action", "History"],
    duration: "2h 32m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "634649",
    title: "Spider-Man: No Way Home",
    overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    backdrop_path: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202206/ezgif-1-c0e4cf8edd_1200x768.jpeg?VersionId=gZj3T5pjRyA..tp1ZXiFTpyHErNh4Myl&size=690:388",
    poster_path: "https://images.unsplash.com/photo-1608889175123-8ec330b86f84?q=80&w=400",
    media_type: "movie",
    release_date: "2021-12-15",
    vote_average: 8.0,
    match_percentage: 96,
    genres: ["Action", "Adventure", "Science Fiction"],
    duration: "2h 28m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "414906",
    title: "The Batman",
    overview: "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbIqK5Gri0ULYtx3m0mGtjPoXGuMmH0UVtNQ&s",
    poster_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=400",
    media_type: "movie",
    release_date: "2022-03-01",
    vote_average: 7.7,
    match_percentage: 92,
    genres: ["Crime", "Mystery", "Thriller", "Action"],
    duration: "2h 56m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "447365",
    title: "Guardians of the Galaxy Vol. 3",
    overview: "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqNBwNRYXgrcjIvXlzXQNpeMiLLp6JCeSO5g&s",
    poster_path: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=400",
    media_type: "movie",
    release_date: "2023-05-03",
    vote_average: 8.0,
    match_percentage: 94,
    genres: ["Action", "Adventure", "Science Fiction"],
    duration: "2h 30m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "120",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    overview: "Young hobbit Frodo Baggins, after inheriting a mysterious ring, must leave his home and embark on an epic quest to destroy the One Ring in the fires of Mount Doom to save Middle-earth from the Dark Lord Sauron.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUQocyBFCLQ_oU0a0mt8mxr1vhZHMiCML9fA&s",
    poster_path: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?q=80&w=400",
    media_type: "movie",
    release_date: "2001-12-18",
    vote_average: 8.4,
    match_percentage: 98,
    genres: ["Adventure", "Fantasy", "Action"],
    duration: "2h 58m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "1726",
    title: "Iron Man",
    overview: "Tony Stark. Genius, billionaire, playboy, philanthropist. One day, Tony is kidnapped and forced to build a devastating weapon. Instead, he builds a high-tech suit of armor and escapes captivity, vowing to protect the world as Iron Man.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBQZ0hREckmLlHBwLe39Uaw6x--LlhBfqn_Q&s",
    poster_path: "https://images.unsplash.com/photo-1608889174653-8152023a9a1d?q=80&w=400",
    media_type: "movie",
    release_date: "2008-04-30",
    vote_average: 7.6,
    match_percentage: 92,
    genres: ["Action", "Science Fiction", "Adventure"],
    duration: "2h 6m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "11324",
    title: "Shutter Island",
    overview: "Worldwide tension increases when US Marshal Teddy Daniels and his new partner Chuck Aule arrive at Shutter Island's Ashecliffe Hospital, a fortress-like asylum for the criminally insane, to investigate the disappearance of a patient.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7rs4BBcfd5ZP8vFKijTwFrMDt_1XbVgZDAw&s",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "movie",
    release_date: "2010-02-18",
    vote_average: 8.2,
    match_percentage: 96,
    genres: ["Drama", "Thriller", "Mystery"],
    duration: "2h 18m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "68718",
    title: "Django Unchained",
    overview: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDIto4EwPHh5InC6pwFt1qAOSpR6CaaXkD0w&s",
    poster_path: "https://images.unsplash.com/photo-1533928298208-27ff66555d8d?q=80&w=400",
    media_type: "movie",
    release_date: "2012-12-25",
    vote_average: 8.1,
    match_percentage: 97,
    genres: ["Drama", "Western"],
    duration: "2h 45m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "1049",
    title: "Zodiac",
    overview: "A cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer, an unidentified serial killer who terrorized the San Francisco Bay Area in the late 1960s and early 1970s.",
    backdrop_path: "https://occ-0-8407-116.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABdqhWsOj7Ife4tv4as-e0Io45GroQgDEG1BmwbAfI40gSE0RjkNbrrw8FIir2jh5mzO0XmLLcDsm0R6HtpcLnfl1aE7i8VQOY6kJ.jpg?r=26d",
    poster_path: "https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=400",
    media_type: "movie",
    release_date: "2007-03-02",
    vote_average: 7.5,
    match_percentage: 91,
    genres: ["Crime", "Mystery", "Thriller", "Drama"],
    duration: "2h 37m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "550",
    title: "Fight Club",
    overview: "A ticking-time-bomb insomniac and a slippery soap salesman channel male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgNKi2BeG8sB1S1JXU8M2JRTFSP6I5MM5k-A&s",
    poster_path: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=400",
    media_type: "movie",
    release_date: "1999-10-15",
    vote_average: 8.4,
    match_percentage: 97,
    genres: ["Drama", "Thriller"],
    duration: "2h 19m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "807",
    title: "Seven",
    overview: "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the seven deadly sins.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZmQlir8P18OrWr5f05dV1KOlFQR8h4P4z7w&s",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "movie",
    release_date: "1995-09-22",
    vote_average: 8.3,
    match_percentage: 97,
    genres: ["Crime", "Mystery", "Thriller"],
    duration: "2h 7m",
    age_rating: "R",
    industry: "hollywood"
  },
  {
    id: "37799",
    title: "The Social Network",
    overview: "On a fall night in 2003, Harvard undergrad and computer programming genius Mark Zuckerberg sits down at his computer and heatedly begins working on a new concept. In a fury of blogging and programming, what begins in his college dorm room soon becomes a global social network.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcorifbasrRX72bbUKdFxxy92gi4P7lsb2LA&s",
    poster_path: "https://images.unsplash.com/photo-1562577309-4932fdd64cd1?q=80&w=400",
    media_type: "movie",
    release_date: "2010-10-01",
    vote_average: 7.7,
    match_percentage: 92,
    genres: ["Drama"],
    duration: "2h 0m",
    age_rating: "PG-13",
    industry: "hollywood"
  },
  {
    id: "11",
    title: "Star Wars: A New Hope",
    overview: "Princess Leia is held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team up with the loveable droid duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Galaxy.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUaVgENX5UnAs3Ig7Mjxp_lWxZKW95z0ve9w&s",
    poster_path: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=400",
    media_type: "movie",
    release_date: "1977-05-25",
    vote_average: 8.2,
    match_percentage: 96,
    genres: ["Action", "Adventure", "Science Fiction"],
    duration: "2h 1m",
    age_rating: "PG",
    industry: "hollywood"
  },

  // --- 35 New Bollywood Movies ---
  {
    id: "20453",
    title: "3 Idiots",
    overview: "Two friends search for their long-lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them idiots.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQke068ATk8PiJoOlqtVZnMgMp-EpqOk4M35Q&s",
    poster_path: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=400",
    media_type: "movie",
    release_date: "2009-12-23",
    vote_average: 8.4,
    match_percentage: 99,
    genres: ["Drama", "Comedy"],
    duration: "2h 50m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "360814",
    title: "Dangal",
    overview: "Mahavir Singh Phogat, a former wrestler, decides to fulfill his dream of winning a gold medal for his country by training his daughters for the Commonwealth Games despite societal stigmas.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS84xOhK_tfWrR_icM0suC-Mh8A8s0xXViSYA&s",
    poster_path: "https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=400",
    media_type: "movie",
    release_date: "2016-12-21",
    vote_average: 8.4,
    match_percentage: 98,
    genres: ["Drama", "Family", "Action"],
    duration: "2h 41m",
    age_rating: "PG",
    industry: "bollywood"
  },
  {
    id: "19662",
    title: "Lagaan: Once Upon a Time in India",
    overview: "In Victorian India, a resilient group of villagers accepts a challenge from a ruthless British officer to play a game of cricket in order to avoid paying high taxes for three years.",
    backdrop_path: "https://i.cdn.newsbytesapp.com/images/l720210615132559.jpeg",
    poster_path: "https://images.unsplash.com/photo-1506461883276-594a12b11cc3?q=80&w=400",
    media_type: "movie",
    release_date: "2001-06-15",
    vote_average: 8.1,
    match_percentage: 95,
    genres: ["Drama", "History", "Sports"],
    duration: "3h 44m",
    age_rating: "PG",
    industry: "bollywood"
  },
  {
    id: "19995",
    title: "Dilwale Dulhania Le Jayenge",
    overview: "Raj and Simran meet on a trip through Europe and fall in love. However, Simran's conservative father has already promised her hand in marriage to a man in India, forcing Raj to follow Simran to win over her traditional family.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR57g8hlEWVZl8UcmKaH6JMbKsOOiLKxMnWaQ&s",
    poster_path: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=80&w=400",
    media_type: "movie",
    release_date: "1995-10-20",
    vote_average: 8.3,
    match_percentage: 97,
    genres: ["Romance", "Drama", "Comedy"],
    duration: "3h 9m",
    age_rating: "PG",
    industry: "bollywood"
  },
  {
    id: "33282",
    title: "Sholay",
    overview: "In the tiny village of Ramgarh, a retired police chief hires two colorful, small-time convicts to capture an infamous, ruthless dacoit named Gabbar Singh who slaughtered his entire family.",
    backdrop_path: "https://ottalert.com.in/wp-content/uploads/2025/12/sholay-1.webp",
    poster_path: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=400",
    media_type: "movie",
    release_date: "1975-08-15",
    vote_average: 8.2,
    match_percentage: 96,
    genres: ["Action", "Adventure", "Drama"],
    duration: "3h 24m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "73937",
    title: "Zindagi Na Milegi Dobara",
    overview: "Three childhood friends set off on a bachelor road trip through stunning Spain. During their adventures, each confronts their deepest fears, heals old wounds, and rediscovers their zest for life.",
    backdrop_path: "https://occ-0-64-58.1.nflxso.net/dnm/api/v6/0DW6CdE4gYtYx8iy3aj8gs9WtXE/AAAABVuBN6ZolgNkgl31u4EDNJDpWxhFf-YmePoli8gmDccMYooJv3UoSx6lxXwd6Vu7_4gRQp0noJ4-vOtx4jPW6VwB6zA.jpg?r=3f4",
    poster_path: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=400",
    media_type: "movie",
    release_date: "2011-07-15",
    vote_average: 8.1,
    match_percentage: 96,
    genres: ["Drama", "Comedy", "Adventure", "Romance"],
    duration: "2h 35m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "180948",
    title: "Yeh Jawaani Hai Deewani",
    overview: "Kabir and Naina bond during a trekking trip. Before Naina can express her feelings, Kabir leaves India to pursue his dream career. They cross paths years later at a friend's wedding and discover that some bonds are timeless.",
    backdrop_path: "https://filmophilia.home.blog/wp-content/uploads/2019/07/1600x1200-yeh_jawaani_hai_deewani_movie_poster.jpg",
    poster_path: "https://images.unsplash.com/photo-1481162854517-d9e353af153d?q=80&w=400",
    media_type: "movie",
    release_date: "2013-05-31",
    vote_average: 7.8,
    match_percentage: 94,
    genres: ["Romance", "Comedy", "Drama"],
    duration: "2h 46m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "273248",
    title: "PK",
    overview: "A naive, innocent alien lands on Earth in Rajasthan, loses his communication device, and asks innocent questions that challenge religious dogmas, leading to an eye-opening journey of self-reflection.",
    backdrop_path: "https://m.media-amazon.com/images/M/MV5BNTE5ZmI1OTYtMzlhNS00NjA0LThiMDYtNmY0YWVhYTY4YjdjXkEyXkFqcGc@._V1_QL75_UX388_.jpg",
    poster_path: "https://images.unsplash.com/photo-1506461883276-594a12b11cc3?q=80&w=400",
    media_type: "movie",
    release_date: "2014-12-18",
    vote_average: 8.1,
    match_percentage: 95,
    genres: ["Comedy", "Drama", "Science Fiction"],
    duration: "2h 33m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "348842",
    title: "Bajrangi Bhaijaan",
    overview: "An earnest Indian man with a magnanimous spirit embarks on a courageous journey to reunite a mute six-year-old Pakistani girl, who got lost in India, with her family in Pakistan.",
    backdrop_path: "https://images.justwatch.com/backdrop/318566002/s640/bajrangi-bhaijaan.jpg",
    poster_path: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=400",
    media_type: "movie",
    release_date: "2015-07-17",
    vote_average: 8.0,
    match_percentage: 96,
    genres: ["Drama", "Action", "Comedy"],
    duration: "2h 39m",
    age_rating: "PG",
    industry: "bollywood"
  },
  {
    id: "205022",
    title: "Chennai Express",
    overview: "A young man's journey to immerse his grandfather's ashes in Rameswaram gets hilariously derailed when he boards the Chennai Express and encounters the daughter of an infamous local don.",
    backdrop_path: "https://occ-0-1223-58.1.nflxso.net/dnm/api/v6/0DW6CdE4gYtYx8iy3aj8gs9WtXE/AAAABZ2hUi_zJbhjG1Z07cSilzVGol4ffSjCaNi1sd_jXBMtcpskOwDBwiDj0lsJ0rqMy9AMoBwQ9kKDyzDtcFRw6_mAAESo9LKkFw.jpg?r=7c0",
    poster_path: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=400",
    media_type: "movie",
    release_date: "2013-08-08",
    vote_average: 6.8,
    match_percentage: 86,
    genres: ["Action", "Comedy", "Romance"],
    duration: "2h 21m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "872906",
    title: "Jawan",
    overview: "A high-octane emotional action-thriller which outlines the journey of a man who is set to rectify the wrongs in the society, motivated by a personal vendetta while keeping a promise made years ago.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLpfySrcAJUSUwpNs78qlsel1kp7QJki3EfQ&s",
    poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400",
    media_type: "movie",
    release_date: "2023-09-07",
    vote_average: 7.3,
    match_percentage: 94,
    genres: ["Action", "Thriller"],
    duration: "2h 49m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "869626",
    title: "Pathaan",
    overview: "An Indian spy takes on the leader of a mercenary group of rogue agents who has a catastrophic plan to unleash a deadly weaponized virus on the country.",
    backdrop_path: "https://substackcdn.com/image/fetch/$s_!sfqW!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F062cf04d-6cd6-4079-9a24-24a8ec93bb35_1280x640.avif",
    poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400",
    media_type: "movie",
    release_date: "2023-01-25",
    vote_average: 6.9,
    match_percentage: 90,
    genres: ["Action", "Thriller", "Adventure"],
    duration: "2h 26m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "781732",
    title: "Animal",
    overview: "A high-tension family drama about a son's fierce, obsessive, and destructive love for his father, and the path of absolute violence he takes to protect him from external enemies.",
    backdrop_path: "https://images.indianexpress.com/2024/01/Poster-of-Animal.jpeg",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "movie",
    release_date: "2023-12-01",
    vote_average: 6.6,
    match_percentage: 88,
    genres: ["Action", "Drama", "Crime"],
    duration: "3h 21m",
    age_rating: "NC-17",
    industry: "bollywood"
  },
  {
    id: "856289",
    title: "Rocky Aur Rani Kii Prem Kahaani",
    overview: "Rocky, a flamboyant Punjabi guy, and Rani, an intellectual Bengali journalist, fall in love despite their vast cultural differences. They decide to live with each other's families for three months before getting married.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ72EoQXXhJuDuTOF2FyUnKh0v_vmFaAl1Nw&s",
    poster_path: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=80&w=400",
    media_type: "movie",
    release_date: "2023-07-28",
    vote_average: 7.2,
    match_percentage: 91,
    genres: ["Romance", "Comedy", "Drama"],
    duration: "2h 48m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "490184",
    title: "Brahmastra Part One: Shiva",
    overview: "A young DJ named Shiva discovers he has an extraordinary connection to the element of fire, and holds the key to awakening a powerful, celestial weapon known as the Brahmastra.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxtKLyPRBvX3j05jqlf2Hgk4NDhE2Z-jaSaQ&s",
    poster_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=400",
    media_type: "movie",
    release_date: "2022-09-09",
    vote_average: 6.7,
    match_percentage: 89,
    genres: ["Fantasy", "Action", "Adventure"],
    duration: "2h 47m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "579974",
    title: "RRR",
    overview: "A fictional saga of two legendary Indian revolutionaries and their journey away from home before they started fighting for their country in the 1920s, featuring staggering action set-pieces.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1d7OntD5DQthXT1dL27e8NYn_1vbrQ2Yeaw&s",
    poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400",
    media_type: "movie",
    release_date: "2022-03-24",
    vote_average: 8.0,
    match_percentage: 97,
    genres: ["Action", "Drama", "History"],
    duration: "3h 7m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "294272",
    title: "Baahubali: The Beginning",
    overview: "A young man raises a small army to rescue his captured biological mother from the clutches of a cruel, tyrannical king who rules a majestic, ancient kingdom.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZJ2s8Re4D03lxEvn1QJy47R5pO5NnS0qvhQ&s",
    poster_path: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?q=80&w=400",
    media_type: "movie",
    release_date: "2015-07-10",
    vote_average: 7.9,
    match_percentage: 93,
    genres: ["Action", "Adventure", "Fantasy"],
    duration: "2h 39m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "350312",
    title: "Baahubali 2: The Conclusion",
    overview: "When Shiva, the son of Bahubali, learns about his heritage, he begins a massive war to defeat the usurper Bhallaladeva and reclaim the ancient, glorious throne of Mahishmati.",
    backdrop_path: "https://origin-staticv2.sonyliv.com/0/bahubali_2_12dec_landscape_thumb.jpg",
    poster_path: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?q=80&w=400",
    media_type: "movie",
    release_date: "2017-04-27",
    vote_average: 8.2,
    match_percentage: 96,
    genres: ["Action", "Fantasy", "Drama"],
    duration: "2h 47m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "245842",
    title: "Drishyam",
    overview: "A common, cable TV operator goes to extreme, meticulous lengths to shield his family from prosecution after they commit an accidental murder of a high-ranking police officer's son.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPTi3LaT-Zow7Y_95a3SmRkItYHkvJvse3Bw&s",
    poster_path: "https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=400",
    media_type: "movie",
    release_date: "2015-07-31",
    vote_average: 8.2,
    match_percentage: 97,
    genres: ["Thriller", "Crime", "Drama"],
    duration: "2h 43m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "972324",
    title: "Drishyam 2",
    overview: "Seven years after the case that shook his family, Vijay Salgaonkar finds himself facing new threats as a relentless investigator reopens the case, threatening to uncover his secrets.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRWC5utEVzx9Dlj3nW-w5tJXk1_ajADFYl9A&s",
    poster_path: "https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=400",
    media_type: "movie",
    release_date: "2022-11-18",
    vote_average: 7.9,
    match_percentage: 95,
    genres: ["Thriller", "Crime", "Drama"],
    duration: "2h 20m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "244458",
    title: "Queen",
    overview: "A Delhi girl from a traditional family decides to go on her pre-booked honeymoon solo after her fiancé calls off the wedding at the eleventh hour, leading to an empowering trip around Paris and Amsterdam.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbw0lNlkJyWQgx05G2N24LFiDe2c0yDZUo8Q&s",
    poster_path: "https://images.unsplash.com/photo-1460881680858-30d872d5b530?q=80&w=400",
    media_type: "movie",
    release_date: "2014-03-07",
    vote_average: 8.1,
    match_percentage: 96,
    genres: ["Drama", "Comedy"],
    duration: "2h 26m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "127532",
    title: "Barfi!",
    overview: "Set in Darjeeling in the 1970s, this is the story of Barfi, a mute and deaf man, and his sweet relationship with two beautiful women: Shruti and Jhilmil, an autistic girl.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd6l-qX3s-m_ukTZQvkZsflAa2VPCuGUatWw&s",
    poster_path: "https://images.unsplash.com/photo-1481162854517-d9e353af153d?q=80&w=400",
    media_type: "movie",
    release_date: "2012-09-13",
    vote_average: 8.1,
    match_percentage: 95,
    genres: ["Drama", "Comedy", "Romance"],
    duration: "2h 30m",
    age_rating: "PG",
    industry: "bollywood"
  },
  {
    id: "535292",
    title: "Gully Boy",
    overview: "A coming-of-age story based on the lives of street rappers in Mumbai's Dharavi slums, documenting their raw struggles and dreams of breaking into mainstream hip-hop.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7BXVuQeEdMFE7K1B4KWxVlNUVGHBqn3A0pA&s",
    poster_path: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?q=80&w=400",
    media_type: "movie",
    release_date: "2019-02-14",
    vote_average: 7.9,
    match_percentage: 93,
    genres: ["Drama", "Music"],
    duration: "2h 33m",
    age_rating: "R",
    industry: "bollywood"
  },
  {
    id: "124157",
    title: "Gangs of Wasseypur - Part 1",
    overview: "A clash between a powerful coal-mining mafioso politician and three generations of a vengeful family in the coal capital of Wasseypur sparks a legendary blood feud.",
    backdrop_path: "https://external-preview.redd.it/netflix-to-stream-5-5-hour-cult-indian-film-gangs-of-v0-24R03W-ncPMOWtbmFoT_Zk3yd4v14Lgt8uG1lHtSknw.jpg?auto=webp&s=c0be01ba2e33fcf96c09b5b1ea4d8411762e9723",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "movie",
    release_date: "2012-06-22",
    vote_average: 8.2,
    match_percentage: 96,
    genres: ["Action", "Crime", "Thriller"],
    duration: "2h 40m",
    age_rating: "NC-17",
    industry: "bollywood"
  },
  {
    id: "124158",
    title: "Gangs of Wasseypur - Part 2",
    overview: "The bloody feud continues in Wasseypur as Definite and Faizal Khan rise to power. Fueled by greed, political nexus, and ancient vengeance, the conflict spirals completely out of control.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVlHM39c6C28CgK80jJprioSaRBBQbxfDh1w&s",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "movie",
    release_date: "2012-08-08",
    vote_average: 8.2,
    match_percentage: 96,
    genres: ["Action", "Crime", "Thriller"],
    duration: "2h 39m",
    age_rating: "NC-17",
    industry: "bollywood"
  },
  {
    id: "508140",
    title: "Andhadhun",
    overview: "A blind piano player gets hilariously and dangerously caught up in a web of murders and deception after he accidentally witnesses the corpse of a former movie star.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3v186Zuy6sT9IyrOheeIu3NNo5uI-vZz5Lw&s",
    poster_path: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=400",
    media_type: "movie",
    release_date: "2018-10-05",
    vote_average: 8.2,
    match_percentage: 97,
    genres: ["Comedy", "Thriller", "Mystery"],
    duration: "2h 19m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "599542",
    title: "Chhichhore",
    overview: "A tragic incident forces an aging father to take a walk down memory lane and share his nostalgic college days alongside his colorful gang of misfit friends who were labeled losers.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThf9X59wpVAZ91xiztQmV6iKG3RpbkIdrbxA&s",
    poster_path: "https://images.unsplash.com/photo-1481162854517-d9e353af153d?q=80&w=400",
    media_type: "movie",
    release_date: "2019-09-06",
    vote_average: 8.0,
    match_percentage: 95,
    genres: ["Drama", "Comedy"],
    duration: "2h 23m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "532292",
    title: "Stree",
    overview: "In the small town of Chanderi, men live in absolute fear of an evil spirit named Stree who abducts men at night during festivals, leaving only their clothes behind.",
    backdrop_path: "https://images.indianexpress.com/2018/08/stree-nale-ba-759.jpg?w=1200",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "movie",
    release_date: "2018-08-31",
    vote_average: 7.5,
    match_percentage: 92,
    genres: ["Comedy", "Horror"],
    duration: "2h 8m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "571384",
    title: "Uri: The Surgical Strike",
    overview: "Divided into five chapters, the film chronicles the strategic, tactical, and highly covert surgical strikes carried out by the Indian Army on terror launchpads in 2016.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnapGElS9oZidqGji0MP_JiCtYPF2w0EntNw&s",
    poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400",
    media_type: "movie",
    release_date: "2019-01-11",
    vote_average: 8.2,
    match_percentage: 96,
    genres: ["Action", "Drama", "History"],
    duration: "2h 18m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "614626",
    title: "Tanhaji: The Unsung Warrior",
    overview: "A spectacular biographical action drama depicting the life of Tanaji Malusare, a 17th-century military leader in the Maratha Empire, and his historic battle at Sinhagad Fort.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFIzuFoUZtSZN0p3dRC9sZ6u920bQejgx_bw&s",
    poster_path: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?q=80&w=400",
    media_type: "movie",
    release_date: "2020-01-10",
    vote_average: 7.6,
    match_percentage: 91,
    genres: ["Action", "History", "Drama"],
    duration: "2h 15m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "581532",
    title: "Kabir Singh",
    overview: "A brilliant but highly self-destructive house surgeon spirals completely out of control into a dark path of drugs, alcohol, and absolute rage after his lover is forced to marry another man.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCtyP8iu0SzS25t1WwehDSCY8u7R21fOQP5w&s",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "movie",
    release_date: "2019-06-21",
    vote_average: 7.1,
    match_percentage: 87,
    genres: ["Drama", "Romance"],
    duration: "2h 55m",
    age_rating: "R",
    industry: "bollywood"
  },
  {
    id: "599292",
    title: "War",
    overview: "An Indian soldier is assigned to eliminate his former mentor, a highly decorated special forces rogue agent, leading to a high-speed, globe-trotting clash of tactical wits.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe-3rnGsyqVMUDSYZ1qMm_Svj2VOdpmkWSkQ&s",
    poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400",
    media_type: "movie",
    release_date: "2019-10-02",
    vote_average: 6.9,
    match_percentage: 90,
    genres: ["Action", "Thriller"],
    duration: "2h 34m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "586289",
    title: "Super 30",
    overview: "Based on the life of brilliant mathematician Anand Kumar, who initiates a revolutionary program in Patna to tutor 30 highly underprivileged but talented students for the elite IIT entrance exams.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0EM3dmuZzIJQqj3j5hH500rAS8e5uJ1u85Q&s",
    poster_path: "https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=400",
    media_type: "movie",
    release_date: "2019-07-12",
    vote_average: 8.0,
    match_percentage: 94,
    genres: ["Drama", "Biography"],
    duration: "2h 34m",
    age_rating: "PG",
    industry: "bollywood"
  },
  {
    id: "350316",
    title: "Padmaavat",
    overview: "Set in medieval Rajasthan, Queen Padmavati's peaceful life is disrupted when a cruel, tyrannical sultan becomes insanely obsessed with her beauty and wages war on her kingdom to capture her.",
    backdrop_path: "https://i.ndtvimg.com/i/2017-12/padmavati_650x400_81514625951.jpg",
    poster_path: "https://images.unsplash.com/photo-1506461883276-594a12b11cc3?q=80&w=400",
    media_type: "movie",
    release_date: "2018-01-25",
    vote_average: 7.9,
    match_percentage: 93,
    genres: ["Drama", "History", "Romance"],
    duration: "2h 44m",
    age_rating: "PG-13",
    industry: "bollywood"
  },
  {
    id: "313364",
    title: "Bajirao Mastani",
    overview: "An epic, tragic historical romance depicting the lives of heroic Maratha Peshwa Bajirao and his second wife, the warrior princess Mastani, amid heavy political opposition.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyfJ7i-xF5BxSayHZtNtH7gCBFl-VpJItyVA&s",
    poster_path: "https://images.unsplash.com/photo-1506461883276-594a12b11cc3?q=80&w=400",
    media_type: "movie",
    release_date: "2015-12-18",
    vote_average: 7.8,
    match_percentage: 92,
    genres: ["Romance", "Drama", "History"],
    duration: "2h 38m",
    age_rating: "PG-13",
    industry: "bollywood"
  }
];

// ----------------------------------------------------
// 2. TV SHOWS (Total: 44 titles - 4 Original + 40 New)
// ----------------------------------------------------
export const mockTVShows = [
  // --- Original 4 Hollywood Shows ---
  {
    id: "119051",
    title: "Wednesday",
    overview: "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her emerging psychic ability, thwart a monstrous killing spree, and solve the supernatural mystery that embroiled her parents 25 years ago.",
    backdrop_path: "https://www.bloomingtonsouthoptimist.org/wp-content/uploads/2023/01/wednesday-netflix.jpg",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2022-11-23",
    vote_average: 8.5,
    match_percentage: 99,
    genres: ["Sci-Fi & Fantasy", "Mystery", "Comedy-Drama"],
    seasons_count: 1,
    age_rating: "TV-14",
    industry: "hollywood",
    seasons: [
      {
        season_number: 1,
        name: "Season 1",
        episodes: [
          { episode_number: 1, title: "Wednesday's Child Is Full of Woe", runtime: "59m", overview: "When Wednesday Addams gets expelled for defending her brother, her parents send her to Nevermore Academy—the boarding school where they fell in love." },
          { episode_number: 2, title: "Woe Is the Loneliest Number", runtime: "48m", overview: "The sheriff questions Wednesday about a strange happening. Wednesday goes up against a fierce rival in the Poe Cup race." },
          { episode_number: 3, title: "Friend or Woe", runtime: "48m", overview: "Wednesday stumbles upon a secret society. During Outreach Day, Nevermore's outcasts mingle with Jericho's normies." },
          { episode_number: 4, title: "Woe What a Night", runtime: "50m", overview: "Wednesday invites Xavier to the Rave'N dance, sparking Tyler's jealousy—but Thing has another trick up his sleeve." },
          { episode_number: 5, title: "You Reap What You Woe", runtime: "51m", overview: "During Parents Weekend, Wednesday digs into her family's past and gets her father arrested for a murder that happened 25 years ago." },
          { episode_number: 6, title: "Woein' Begone", runtime: "49m", overview: "Wednesday's friends throw her a surprise birthday party. They mean well, but she'd rather solve the monstrous murders." },
          { episode_number: 7, title: "If You Don't Woe Me by Now", runtime: "47m", overview: "Uncle Fester visits Nevermore and shares his theories on the monster. Wednesday reluctantly agrees to go on a date with Tyler." },
          { episode_number: 8, title: "A Murder of Woes", runtime: "52m", overview: "Wednesday clashes with Principal Weems, then faces off against an ancient evil that threatens Nevermore and all outcasts." }
        ]
      }
    ]
  },
  {
    id: "66732",
    title: "Stranger Things",
    overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    backdrop_path: "https://deadline.com/wp-content/uploads/2025/12/stranger-things-season-5-netflix-posters.jpg?w=681&h=383&crop=1",
    poster_path: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=400",
    media_type: "tv",
    first_air_date: "2016-07-15",
    vote_average: 8.6,
    match_percentage: 97,
    genres: ["Drama", "Sci-Fi & Fantasy", "Mystery"],
    seasons_count: 4,
    age_rating: "TV-14",
    industry: "hollywood",
    seasons: [
      {
        season_number: 1,
        name: "Season 1",
        episodes: [
          { episode_number: 1, title: "Chapter One: The Vanishing of Will Byers", runtime: "47m", overview: "On his way home from a friend's house, young Will sees something terrifying. Nearby, a sinister secret lurks in the depths of a government lab." },
          { episode_number: 2, title: "Chapter Two: The Weirdo on Maple Street", runtime: "55m", overview: "Lucas, Mike and Dustin try to talk to the girl they found in the woods. Hopper questions an anxious Joyce about a phone call." },
          { episode_number: 3, title: "Chapter Three: Holly, Jolly", runtime: "51m", overview: "An increasingly concerned Nancy looks for Barb and finds out Jonathan is hiding something. Joyce believes Will is trying to talk to her." }
        ]
      }
    ]
  },
  {
    id: "1399",
    title: "Breaking Bad",
    overview: "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years to live. To secure his family's financial future, he decides to enter the dangerous world of drugs and crime.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpck5d_aKC1UETZJ099ePxK2oaVSGDQFiQog&s",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2008-01-20",
    vote_average: 8.9,
    match_percentage: 99,
    genres: ["Drama", "Crime"],
    seasons_count: 5,
    age_rating: "TV-MA",
    industry: "hollywood",
    seasons: [
      {
        season_number: 1,
        name: "Season 1",
        episodes: [
          { episode_number: 1, title: "Pilot", runtime: "58m", overview: "Diagnosed with terminal lung cancer, chemistry teacher Walter White teams up with his former student Jesse Pinkman to manufacture and sell crystal meth." },
          { episode_number: 2, title: "Cat's in the Bag...", runtime: "48m", overview: "Walt and Jesse try to dispose of the two bodies in the RV, which becomes increasingly complicated when one of them turns out to be alive." }
        ]
      }
    ]
  },
  {
    id: "93405",
    title: "Squid Game",
    overview: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
    backdrop_path: "https://cdn.dribbble.com/userupload/43794838/file/original-b6c50a20ee23b65605dd0aadbbe7b88b.jpg?resize=752x&vertical=center",
    poster_path: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?q=80&w=400",
    media_type: "tv",
    first_air_date: "2021-09-17",
    vote_average: 7.8,
    match_percentage: 95,
    genres: ["Action & Adventure", "Mystery", "Drama"],
    seasons_count: 1,
    age_rating: "TV-MA",
    industry: "hollywood",
    seasons: [
      {
        season_number: 1,
        name: "Season 1",
        episodes: [
          { episode_number: 1, title: "Red Light, Green Light", runtime: "60m", overview: "Hoping to win easy money, a broke Gi-hun agrees to take part in an enigmatic game. But as the first round begins, unexpected horrors unfold." }
        ]
      }
    ]
  },

  // --- 20 New Hollywood TV Shows (Leverages generateMockSeasons!) ---
  {
    id: "12140",
    title: "Game of Thrones",
    overview: "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north.",
    backdrop_path: "https://i.pinimg.com/originals/82/01/5c/82015cc18436c4514c02e1be5e9667cb.jpg",
    poster_path: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?q=80&w=400",
    media_type: "tv",
    first_air_date: "2011-04-17",
    vote_average: 8.4,
    match_percentage: 98,
    genres: ["Sci-Fi & Fantasy", "Drama", "Action & Adventure"],
    seasons_count: 8,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "100088",
    title: "The Last of Us",
    overview: "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone in a post-apocalyptic saga.",
    backdrop_path: "https://static0.srcdn.com/wordpress/wp-content/uploads/2019/01/The-Last-of-Us-and-What-Still-Remains.jpg?w=1200&h=675&fit=crop",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2023-01-15",
    vote_average: 8.6,
    match_percentage: 97,
    genres: ["Drama", "Action & Adventure"],
    seasons_count: 1,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "76331",
    title: "Succession",
    overview: "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down from the company.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRt9esOB_5eZKfIFN-6i1AP1Siy4iBN2gq0Zw&s",
    poster_path: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=400",
    media_type: "tv",
    first_air_date: "2018-06-03",
    vote_average: 8.3,
    match_percentage: 96,
    genres: ["Drama", "Comedy"],
    seasons_count: 4,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "87108",
    title: "Chernobyl",
    overview: "A spectacular dramatization of the true story of the unprecedented 1986 nuclear accident, documenting the brave men and women who sacrificed themselves to save Europe from catastrophic disaster.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzY9Fc-nZD_k4PBEA2GiiQCmBUu40CIH0O6A&s",
    poster_path: "https://images.unsplash.com/photo-1447069387593-a5de0862481e?q=80&w=400",
    media_type: "tv",
    first_air_date: "2019-05-06",
    vote_average: 8.6,
    match_percentage: 98,
    genres: ["Drama", "History"],
    seasons_count: 1,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "2316",
    title: "The Office (US)",
    overview: "This mockumentary frames the humorous, mundane, and cringe-inducing everyday lives of colorful office workers at the Dunder Mifflin paper company in Scranton, Pennsylvania.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSswxdOOPs1z01fUox9vrEEAndO_d1eVeZ_A&s",
    poster_path: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2005-03-24",
    vote_average: 8.4,
    match_percentage: 95,
    genres: ["Comedy"],
    seasons_count: 9,
    age_rating: "TV-14",
    industry: "hollywood"
  },
  {
    id: "1668",
    title: "Friends",
    overview: "The classic sitcom follows the personal and professional lives of six twenty-to-thirty-something friends living in Manhattan as they navigate romance, careers, and coffee.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs1cPwsXT_GNLEE_DDyBovOL-71IGVvbYSPA&s",
    poster_path: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=400",
    media_type: "tv",
    first_air_date: "1994-09-22",
    vote_average: 8.4,
    match_percentage: 96,
    genres: ["Comedy", "Romance"],
    seasons_count: 10,
    age_rating: "TV-14",
    industry: "hollywood"
  },
  {
    id: "60059",
    title: "Better Call Saul",
    overview: "This acclaimed prequel spin-off of Breaking Bad outlines the journey of earnest lawyer Jimmy McGill as he slowly transforms into the colorful, highly corrupt defense attorney Saul Goodman.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXP36xJ2md0liurwnnEQaeyaAcH-WMuDUMXA&s",
    poster_path: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=400",
    media_type: "tv",
    first_air_date: "2015-02-08",
    vote_average: 8.6,
    match_percentage: 97,
    genres: ["Drama", "Crime"],
    seasons_count: 6,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "76479",
    title: "The Boys",
    overview: "A fun and highly irreverent take on what happens when superheroes, who are as popular as celebrities, abuse their superpowers rather than use them for good.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNyQ_C1W-dpbg--BoQ21PbV3Y5Av4DaIJsCw&s",
    poster_path: "https://images.unsplash.com/photo-1608889175123-8ec330b86f84?q=80&w=400",
    media_type: "tv",
    first_air_date: "2019-07-25",
    vote_average: 8.4,
    match_percentage: 96,
    genres: ["Sci-Fi & Fantasy", "Action & Adventure", "Drama"],
    seasons_count: 4,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "95396",
    title: "Severance",
    overview: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives, embarking on a quest to expose a deep web of corporate conspiracies.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRgCe5f-vvhF12Vjj-ftEgUHhoiOev9ydHgQ&s",
    poster_path: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2022-02-17",
    vote_average: 8.4,
    match_percentage: 94,
    genres: ["Drama", "Mystery", "Sci-Fi & Fantasy"],
    seasons_count: 1,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "65494",
    title: "The Crown",
    overview: "A highly acclaimed historical drama following the political rivalries, romances, and historical events of Queen Elizabeth II's reign, documenting the personal lives that shaped the 20th century.",
    backdrop_path: "https://i.ytimg.com/vi/C6KC-KsxRrE/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAz93iQnqjXH49sfs5UvtfUfXyhJg",
    poster_path: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=400",
    media_type: "tv",
    first_air_date: "2016-11-04",
    vote_average: 8.2,
    match_percentage: 92,
    genres: ["Drama", "History"],
    seasons_count: 6,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "63351",
    title: "Narcos",
    overview: "A gritty, documentary-style chronicle of the real-life rise and spread of cocaine drug cartels across the globe, and the relentless law enforcement efforts that met them in brutal conflict.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt_nI8KKJ9AhywMqTEq1WCaQc-lfh4jFKxEw&s",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2015-08-28",
    vote_average: 8.3,
    match_percentage: 96,
    genres: ["Drama", "Crime"],
    seasons_count: 3,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "97546",
    title: "Ted Lasso",
    overview: "An American college football coach is unexpectedly hired to manage a struggling British soccer team, bringing his infectious optimism and homemade biscuits to win over skeptical players.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBtirHCFMcqGokHNYeKEipiatmBOjdNdYC4w&s",
    poster_path: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=400",
    media_type: "tv",
    first_air_date: "2020-08-14",
    vote_average: 8.5,
    match_percentage: 95,
    genres: ["Comedy", "Drama"],
    seasons_count: 3,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "42009",
    title: "Black Mirror",
    overview: "A sci-fi anthology series which taps into our collective unease about the modern world, with each stand-alone episode exploring themes of contemporary techno-paranoia.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxA4pa5vN8x7U0xTrC7z079O1JuGrFkufqzA&s",
    poster_path: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=400",
    media_type: "tv",
    first_air_date: "2011-12-04",
    vote_average: 8.3,
    match_percentage: 96,
    genres: ["Sci-Fi & Fantasy", "Drama", "Mystery"],
    seasons_count: 6,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "74204",
    title: "Mindhunter",
    overview: "Set in the late 1970s, two FBI agents expand criminal science by delving into the psychology of murder and awkwardly bonding with real-life serial killers.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqjc8TwbmwYtV9Guo8o_kM80iTGW9jMdZCyw&s",
    poster_path: "https://images.unsplash.com/photo-1453733190148-c44698c26588?q=400",
    media_type: "tv",
    first_air_date: "2017-10-13",
    vote_average: 8.4,
    match_percentage: 94,
    genres: ["Drama", "Crime", "Mystery"],
    seasons_count: 2,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "119052",
    title: "The Bear",
    overview: "A young, award-winning fine-dining chef returns home to Chicago to run his family's gritty sandwich shop after a heartbreaking tragedy, battling debt, kitchen chaos, and stubborn staff.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtbMO44z0PwFIge7x2DPyOdvTyE83fL6zbXw&s",
    poster_path: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=400",
    media_type: "tv",
    first_air_date: "2022-06-23",
    vote_average: 8.5,
    match_percentage: 96,
    genres: ["Drama", "Comedy"],
    seasons_count: 2,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "215077",
    title: "Beef",
    overview: "A wild, high-speed road rage incident between two struggling strangers—an unsuccessful contractor and an unfulfilled self-made entrepreneur—sparks an escalating, obsessive feud.",
    backdrop_path: "https://images.squarespace-cdn.com/content/v1/65c5568ee7c0a0155d92045e/8ac1cbfd-a0d2-4f3a-a20f-b3dc085d681c/Netflix-BEEF-Ali-Wong-Steven-Yeun-Key-Art-Poster-Design-Juan-Luis-Garcia-1500px.jpg",
    poster_path: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=80&w=400",
    media_type: "tv",
    first_air_date: "2023-04-06",
    vote_average: 8.1,
    match_percentage: 93,
    genres: ["Comedy", "Drama"],
    seasons_count: 1,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "82856",
    title: "The Mandalorian",
    overview: "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic, protecting a highly mysterious child.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcU3yM9OPhnI2ca4wj5XmqepUq2aO1zJ8gdg&s",
    poster_path: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=400",
    media_type: "tv",
    first_air_date: "2019-11-12",
    vote_average: 8.4,
    match_percentage: 96,
    genres: ["Sci-Fi & Fantasy", "Action & Adventure"],
    seasons_count: 3,
    age_rating: "TV-14",
    industry: "hollywood"
  },
  {
    id: "84958",
    title: "Loki",
    overview: "The mercurial villain Loki resumes his role as the God of Mischief in a thrilling, time-bending new series that takes place immediately after the events of Avengers: Endgame.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3hQt1C53cYGV-hjmdEdVYRvbxo8kjhZR7yQ&s",
    poster_path: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=400",
    media_type: "tv",
    first_air_date: "2021-06-09",
    vote_average: 8.2,
    match_percentage: 95,
    genres: ["Sci-Fi & Fantasy", "Action & Adventure"],
    seasons_count: 2,
    age_rating: "TV-14",
    industry: "hollywood"
  },
  {
    id: "60625",
    title: "Rick and Morty",
    overview: "An brilliant but highly unstable, alcoholic scientific genius drags his young, timid grandson on dangerous, mind-bending adventures across the infinite multiverse.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAqZ2oGXxVRV-TeAg2B2Uyd0ljAXMqFBFthA&s",
    poster_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=400",
    media_type: "tv",
    first_air_date: "2013-12-02",
    vote_average: 8.7,
    match_percentage: 98,
    genres: ["Animation", "Comedy", "Sci-Fi & Fantasy"],
    seasons_count: 7,
    age_rating: "TV-MA",
    industry: "hollywood"
  },
  {
    id: "19885",
    title: "Sherlock",
    overview: "A modern-day update of Arthur Conan Doyle's classic detective stories, following eccentric sleuth Sherlock Holmes and his veteran flatmate John Watson solving complex London mysteries.",
    backdrop_path: "https://www.whats-on-netflix.com/wp-content/uploads/2016/04/sherlock-season-4-netflix-1024x576.jpg",
    poster_path: "https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=400",
    media_type: "tv",
    first_air_date: "2010-07-25",
    vote_average: 8.5,
    match_percentage: 97,
    genres: ["Drama", "Crime", "Mystery"],
    seasons_count: 4,
    age_rating: "TV-14",
    industry: "hollywood"
  },

  // --- 20 New Bollywood/Indian TV Shows ---
  {
    id: "79352",
    title: "Sacred Games",
    overview: "A chaotic link in their pasts leads an honest, struggling police officer to a fugitive gang lord whose enigmatic, ominous warning prompts a high-stakes race to save Mumbai from utter catastrophe.",
    backdrop_path: "https://static.india.com/wp-content/uploads/2018/08/Saif-Ali-Khan-Nawazuddin-Siddiqui-Sacred-games.jpg?impolicy=Medium_Widthonly&w=400",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2018-07-06",
    vote_average: 8.5,
    match_percentage: 98,
    genres: ["Crime", "Drama", "Thriller"],
    seasons_count: 2,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "84105",
    title: "Mirzapur",
    overview: "A shocking incident at a wedding procession ignites a series of events, entangling the lives of two ordinary brothers with a lawless, powerful mafia don and his unhinged, power-hungry son.",
    backdrop_path: "https://static.digit.in/Mirzapur-3.png",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2018-11-16",
    vote_average: 8.4,
    match_percentage: 98,
    genres: ["Action", "Crime", "Thriller"],
    seasons_count: 3,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "92452",
    title: "The Family Man",
    overview: "The thrilling journey of a middle-class common man who secretly works as a high-ranking intelligence officer for a special cell of the National Investigation Agency, struggling to balance high-stakes national security with familial duties.",
    backdrop_path: "https://m.media-amazon.com/images/S/pv-target-images/04b53844c44bc3c4fa52415bd34ce29a932a40986d7b9ec6189b2f3bed76e714.jpg",
    poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400",
    media_type: "tv",
    first_air_date: "2019-09-20",
    vote_average: 8.6,
    match_percentage: 97,
    genres: ["Action & Adventure", "Comedy", "Drama"],
    seasons_count: 2,
    age_rating: "TV-14",
    industry: "bollywood"
  },
  {
    id: "97224",
    title: "Panchayat",
    overview: "An engineering graduate takes up a low-paying job of a secretary in a remote, rural village Panchayat in Uttar Pradesh, encountering colorful villagers, local politics, and rustic life.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgIy1DfxSygC4JJyqYaAdQQoYaJ3wyS2MB3g&s",
    poster_path: "https://images.unsplash.com/photo-1506461883276-594a12b11cc3?q=80&w=400",
    media_type: "tv",
    first_air_date: "2020-04-03",
    vote_average: 8.7,
    match_percentage: 99,
    genres: ["Comedy", "Drama"],
    seasons_count: 3,
    age_rating: "TV-PG",
    industry: "bollywood"
  },
  {
    id: "111188",
    title: "Scam 1992: The Harshad Mehta Story",
    overview: "Set in 1980s & 90s Bombay, this spectacular biographical series documents the spectacular rise and catastrophic fall of Harshad Mehta, a charismatic stockbroker who triggered a massive, systemic stock market scam.",
    backdrop_path: "https://www.myfandom.store/media/magefan_blog/scam_1992_the_harshad_mehta_story.png",
    poster_path: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=400",
    media_type: "tv",
    first_air_date: "2020-10-09",
    vote_average: 8.9,
    match_percentage: 99,
    genres: ["Drama", "Biography", "Crime"],
    seasons_count: 1,
    age_rating: "TV-14",
    industry: "bollywood"
  },
  {
    id: "102148",
    title: "Paatal Lok",
    overview: "A cynical, down-on-his-luck Delhi police officer gets assigned to investigate a high-profile assassination attempt, leading him deep into the dark, terrifying underworld of Paatal Lok.",
    backdrop_path: "https://miro.medium.com/0*QLk6tewcEBDF2TUz.jpeg",
    poster_path: "https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=400",
    media_type: "tv",
    first_air_date: "2020-05-15",
    vote_average: 8.3,
    match_percentage: 95,
    genres: ["Crime", "Drama", "Thriller"],
    seasons_count: 1,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "97120",
    title: "Delhi Crime",
    overview: "Based on real-life case files, Delhi Crime follows the meticulous, high-tension investigation led by a determined female police commissioner following a heinous, nationwide shock crime in Delhi.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiS1bP8YclXO_6r1evjcu7Z_hA3esJtus0Ug&s",
    poster_path: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=400",
    media_type: "tv",
    first_air_date: "2019-03-22",
    vote_average: 8.5,
    match_percentage: 97,
    genres: ["Drama", "Crime"],
    seasons_count: 2,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "89113",
    title: "Kota Factory",
    overview: "Set in Kota, the coaching hub of India, this critically acclaimed monochrome drama portrays the lives, struggles, academic pressures, and romances of engineering aspirants prepping for the prestigious IIT entrance exams.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2wPy_08C0bEL7nxQdzaBHQNdD3tEpNFZu9g&s",
    poster_path: "https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=400",
    media_type: "tv",
    first_air_date: "2019-04-16",
    vote_average: 8.6,
    match_percentage: 98,
    genres: ["Drama", "Comedy"],
    seasons_count: 3,
    age_rating: "TV-14",
    industry: "bollywood"
  },
  {
    id: "92996",
    title: "Gullak",
    overview: "Centered in a quaint, middle-class North Indian town, this heart-warming comedy-drama chronicles the everyday anecdotes, sweet disagreements, and budget constraints of the lovable Mishra family.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLaaVKAMMJTRY2MicweXKChsNFN-l_Hl25Dw&s",
    poster_path: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=80&w=400",
    media_type: "tv",
    first_air_date: "2019-06-27",
    vote_average: 8.5,
    match_percentage: 96,
    genres: ["Comedy", "Drama", "Family"],
    seasons_count: 4,
    age_rating: "TV-G",
    industry: "bollywood"
  },
  {
    id: "125638",
    title: "Aspirants",
    overview: "The story outlines the complex journey of three childhood friends prep-studying in Old Rajinder Nagar, Delhi, for the highly competitive UPSC civil services examination, highlighting their struggles, friendship, and adult realizations.",
    backdrop_path: "https://cf-images.assettype.com/cinemaexpress%2F2026-03-02%2Fv47apk21%2FTVF-Aspirants.jpg?w=480&auto=format%2Ccompress&fit=max",
    poster_path: "https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=400",
    media_type: "tv",
    first_air_date: "2021-04-07",
    vote_average: 8.5,
    match_percentage: 97,
    genres: ["Drama"],
    seasons_count: 2,
    age_rating: "TV-14",
    industry: "bollywood"
  },
  {
    id: "196624",
    title: "Farzi",
    overview: "A brilliant, small-time artist designs an incredibly high-fidelity counterfeit currency note, pulling him into a high-stakes game of cat-and-mouse with a relentless, fiery task force officer.",
    backdrop_path: "https://i.pinimg.com/736x/29/c4/78/29c4784ea4e78cf18fa27dae59472f0c.jpg",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2023-02-10",
    vote_average: 8.4,
    match_percentage: 96,
    genres: ["Crime", "Drama", "Thriller", "Action"],
    seasons_count: 1,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "204526",
    title: "Guns & Gulaabs",
    overview: "In the lawless, retro town of Gulaabganj, an unexpected cartel deal entangles a nostalgic mechanic, a reluctant heir to a crime family, and an earnest narcotics officer in a hilarious, retro-styled dark comedy thriller.",
    backdrop_path: "https://akm-img-a-in.tosshub.com/indiatoday/images/media_bank/202308/guns-and-gulaabs-183150-16x9.jpeg?VersionId=ib1ciq5E4eWIyu.ttk_RD3vncidu00Rf",
    poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400",
    media_type: "tv",
    first_air_date: "2023-08-18",
    vote_average: 7.8,
    match_percentage: 91,
    genres: ["Comedy", "Crime", "Thriller", "Romance"],
    seasons_count: 1,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "228542",
    title: "Kohrra",
    overview: "When a wealthy NRI bridegroom is found dead in the countryside of Punjab just days before his wedding, two tired police officers must unpack a deep web of family secrets, deceit, and personal turmoil to solve it.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmWKFlYo9SFCGn3bke0HbV9MfrRYHQz8FdVw&s",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2023-07-15",
    vote_average: 7.7,
    match_percentage: 90,
    genres: ["Crime", "Drama", "Mystery"],
    seasons_count: 1,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "219532",
    title: "Jubilee",
    overview: "A poetic, grand historical drama set in the golden age of Hindi cinema, documenting the ambitions, dark compromises, romances, and rise to stardom of iconic filmmakers and actors in post-independence Bombay.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSblu2LjnBSYYUdquQyTItsLRJsi25sXVqR_A&s",
    poster_path: "https://images.unsplash.com/photo-1460881680858-30d872d5b530?q=80&w=400",
    media_type: "tv",
    first_air_date: "2023-04-07",
    vote_average: 8.3,
    match_percentage: 94,
    genres: ["Drama", "History"],
    seasons_count: 1,
    age_rating: "TV-14",
    industry: "bollywood"
  },
  {
    id: "90024",
    title: "Made in Heaven",
    overview: "Two wedding planners in Delhi navigate the luxurious, modern, and highly traditional demands of upscale Indian weddings, exposing complex societal prejudices, hidden agendas, and their own messy personal lives.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgwlH1B5_nax79eLoqpcBQHbKhQXnT6o3UTA&s",
    poster_path: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=80&w=400",
    media_type: "tv",
    first_air_date: "2019-03-08",
    vote_average: 8.2,
    match_percentage: 93,
    genres: ["Drama", "Romance"],
    seasons_count: 2,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "109289",
    title: "Breathe: Into the Shadows",
    overview: "A desperate father goes to terrifying, illegal extremes to rescue his kidnapped young daughter from a mysterious, masked kidnapper who demands he commit murders in exchange.",
    backdrop_path: "https://upload.wikimedia.org/wikipedia/en/0/0a/Breathe_Into_The_Shadows_Poster.jpeg",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2020-07-10",
    vote_average: 7.6,
    match_percentage: 90,
    genres: ["Crime", "Drama", "Thriller", "Mystery"],
    seasons_count: 2,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "97560",
    title: "Special OPS",
    overview: "An intelligence officer tracks a highly elusive, master terror operative across 19 years and multiple countries, deploying five covert agents in deep cover across the globe.",
    backdrop_path: "https://img1.hotstarext.com/image/upload/f_auto/sources/r1/cms/prod/9789/1757951169789-i",
    poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400",
    media_type: "tv",
    first_air_date: "2020-03-17",
    vote_average: 8.4,
    match_percentage: 95,
    genres: ["Action & Adventure", "Crime", "Thriller"],
    seasons_count: 2,
    age_rating: "TV-14",
    industry: "bollywood"
  },
  {
    id: "98246",
    title: "Asur: Welcome to Your Dark Side",
    overview: "A brilliant forensic expert teams up with his former mentor at CBI, plunging into a high-stakes, psychological chase with a serial killer who styles his murders after ancient Indian mythology.",
    backdrop_path: "https://images.justwatch.com/backdrop/340111590/s640/asur.jpg",
    poster_path: "https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=400",
    media_type: "tv",
    first_air_date: "2020-03-02",
    vote_average: 8.5,
    match_percentage: 97,
    genres: ["Crime", "Drama", "Thriller", "Mystery"],
    seasons_count: 2,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "109848",
    title: "Aarya",
    overview: "A loving mother is forced to join a dangerous drug cartel to protect her three children from powerful, ruthless mafia families after her husband is mysteriously assassinated.",
    backdrop_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnPebsTjPOvVzmyV9AppHw2KeiEkDYCxl0Jw&s",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400",
    media_type: "tv",
    first_air_date: "2020-06-19",
    vote_average: 7.9,
    match_percentage: 91,
    genres: ["Drama", "Crime", "Thriller"],
    seasons_count: 3,
    age_rating: "TV-MA",
    industry: "bollywood"
  },
  {
    id: "215638",
    title: "Taaza Khabar",
    overview: "A humble sanitation worker in Mumbai discovers he has a magical power to receive news alerts of the future hours before they happen, initiating a high-speed climb up the ranks of wealth and greed.",
    backdrop_path: "https://m.media-amazon.com/images/M/MV5BYzJmYTcxMGQtMjI1Yi00N2QyLWEzNTctMTM4NTQwNTE1ODBlXkEyXkFqcGc@._V1_.jpg",
    poster_path: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?q=80&w=400",
    media_type: "tv",
    first_air_date: "2023-01-06",
    vote_average: 7.6,
    match_percentage: 90,
    genres: ["Comedy", "Drama", "Fantasy"],
    seasons_count: 1,
    age_rating: "TV-14",
    industry: "bollywood"
  }
];

export const allMockData = [...mockMovies, ...mockTVShows];
